#Requires -Version 5.1
<#
    Install (or refresh) lgrow's Windows schedule. The counterpart to
    install-cron.sh, which only works on Linux and macOS.

    Idempotent: every task is registered under the \lgrow\ folder in Task
    Scheduler with -Force, so re-running replaces rather than duplicates. Run
    with `remove` to take the whole folder out again.

    Like the cron installer, this generates a wrapper script instead of calling
    lgrow directly, and for the same reason: a scheduled task starts with a
    minimal environment, so `gemini` (installed by npm, usually under
    %APPDATA%\npm or nvm) would not be found and every AI call would fail with
    an auth error that looks like a login problem. The wrapper pins the PATH
    that exists right now, at install time.

    Two things the cron version never has to worry about:

      * Task Scheduler refuses to start a task on battery power by default,
        which on a laptop means the schedule silently never runs. Fixed with
        -AllowStartIfOnBatteries.
      * Output is redirected to a log file, so Python's stdout is not a console
        and falls back to the legacy code page. lgrow prints check marks and box
        drawing characters, which then raise UnicodeEncodeError. Fixed by
        setting PYTHONUTF8=1 in the wrapper.

    Usage:
        powershell -ExecutionPolicy Bypass -File scripts\install-schedule.ps1
        powershell -ExecutionPolicy Bypass -File scripts\install-schedule.ps1 remove
#>

param(
    [ValidateSet('install', 'remove')]
    [string]$Action = 'install'
)

$ErrorActionPreference = 'Stop'

$TaskFolder = '\lgrow\'
$Root       = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$Wrapper    = Join-Path $Root 'scripts\lgrow-task.cmd'
$LogDir     = Join-Path $Root 'data\logs'

# Task name -> the `lgrow run` subcommand it invokes.
$Tasks = [ordered]@{
    'crawl'       = 'Fetch, score and queue jobs; prepare materials for the best matches.'
    'publish-due' = 'Publish anything whose scheduled slot has arrived (one post per run).'
    'weekly'      = "Draft next week's posts, refresh the LinkedIn token, list follow-ups."
    'catchup'     = 'Replay whatever was missed while this machine was asleep or shut down.'
}

# ── remove ───────────────────────────────────────────────────────────────────

function Remove-Schedule {
    param([switch]$Quiet)

    $existing = Get-ScheduledTask -TaskPath $TaskFolder -ErrorAction SilentlyContinue
    if (-not $existing) {
        if (-not $Quiet) { Write-Host 'no lgrow tasks were registered' }
        return
    }
    foreach ($task in $existing) {
        Unregister-ScheduledTask -TaskName $task.TaskName -TaskPath $TaskFolder -Confirm:$false
        Write-Host "  removed $($task.TaskName)"
    }
    # No cmdlet deletes an empty task folder; the COM API is the only route.
    try {
        $service = New-Object -ComObject 'Schedule.Service'
        $service.Connect()
        $service.GetFolder('\').DeleteFolder($TaskFolder.Trim('\'), 0)
    } catch {
        # An orphaned empty folder is cosmetic. Not worth failing over.
    }
}

if ($Action -eq 'remove') {
    Remove-Schedule
    Write-Host ''
    Write-Host 'done. lgrow will no longer run on a schedule.'
    exit 0
}

# ── locate lgrow ─────────────────────────────────────────────────────────────

$VenvLgrow = Join-Path $Root '.venv\Scripts\lgrow.exe'
if (Test-Path $VenvLgrow) {
    $LgrowBin = $VenvLgrow
} else {
    $onPath = Get-Command 'lgrow' -ErrorAction SilentlyContinue
    if ($onPath) {
        $LgrowBin = $onPath.Source
    } else {
        Write-Error @"
cannot find lgrow. Install it first:
    cd '$Root'
    py -3 -m venv .venv
    .venv\Scripts\pip install -e .
"@
        exit 1
    }
}

# ── the wrapper ──────────────────────────────────────────────────────────────

$GeminiDir = ''
$gemini = Get-Command 'gemini' -ErrorAction SilentlyContinue
if ($gemini) {
    $GeminiDir = Split-Path -Parent $gemini.Source
}

# A literal % in a batch file starts a variable reference, so any that appear in
# the captured PATH have to be doubled.
$PinnedPath = $env:PATH
if ($GeminiDir -and ($PinnedPath -notlike "*$GeminiDir*")) {
    $PinnedPath = "$GeminiDir;$PinnedPath"
}
$PinnedPath = $PinnedPath -replace '%', '%%'

$stamp = (Get-Date).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ssZ')

$wrapperBody = @"
@echo off
REM Generated by scripts\install-schedule.ps1 on $stamp.
REM Re-run that script if node moves and the Gemini CLI stops being found.

REM A scheduled task inherits almost no PATH. This is the PATH captured at
REM install time, which is what makes `gemini` reachable from a scheduled run.
set "PATH=$PinnedPath"
set "LGROW_HOME=$Root"

REM stdout below is a file, not a console, so Python would encode with the
REM legacy code page and lgrow's check marks would raise UnicodeEncodeError.
set "PYTHONUTF8=1"

if not exist "%LGROW_HOME%\data\logs" mkdir "%LGROW_HOME%\data\logs"

"$LgrowBin" run %* >> "%LGROW_HOME%\data\logs\schedule.log" 2>&1
exit /b %ERRORLEVEL%
"@

New-Item -ItemType Directory -Force -Path $LogDir | Out-Null
# cmd.exe reads batch files in the OEM code page, not ANSI or UTF-8. Writing
# ASCII would mangle a PATH containing a non-English username.
Set-Content -Path $Wrapper -Value $wrapperBody -Encoding Oem
Write-Host "wrote $Wrapper"

# ── triggers ─────────────────────────────────────────────────────────────────
# Times are local. Deliberately off the hour so we are not competing with every
# other scheduled task on the machine at :00.

function New-RepeatingTrigger {
    param([int]$Minutes)
    # An indefinite repetition duration is TimeSpan.MaxValue, which some builds
    # of the ScheduledTasks module reject. Ten years is indistinguishable.
    $start = (Get-Date).Date.AddMinutes(2)
    try {
        return New-ScheduledTaskTrigger -Once -At $start `
            -RepetitionInterval (New-TimeSpan -Minutes $Minutes) `
            -RepetitionDuration ([TimeSpan]::MaxValue)
    } catch {
        return New-ScheduledTaskTrigger -Once -At $start `
            -RepetitionInterval (New-TimeSpan -Minutes $Minutes) `
            -RepetitionDuration (New-TimeSpan -Days 3650)
    }
}

$catchupTrigger = New-ScheduledTaskTrigger -AtLogOn
# Mirrors `@reboot sleep 120` — give the network a chance to come up first.
$catchupTrigger.Delay = 'PT2M'

$Triggers = @{
    'crawl'       = (New-ScheduledTaskTrigger -Daily -At '07:07')
    'publish-due' = (New-RepeatingTrigger -Minutes 30)
    'weekly'      = (New-ScheduledTaskTrigger -Weekly -DaysOfWeek Sunday -At '18:00')
    'catchup'     = $catchupTrigger
}

# StartWhenAvailable is the closest Task Scheduler gets to lgrow's own catchup:
# a task missed while the machine was off runs once it is back.
#
# The battery flags are not optional on a laptop. Without them Windows skips the
# task entirely while unplugged and never tells you.
$Settings = New-ScheduledTaskSettingsSet `
    -StartWhenAvailable `
    -AllowStartIfOnBatteries `
    -DontStopIfGoingOnBatteries `
    -MultipleInstances IgnoreNew `
    -ExecutionTimeLimit (New-TimeSpan -Hours 2)

# ── register ─────────────────────────────────────────────────────────────────

Remove-Schedule -Quiet

# S4U runs as you, without a stored password and without flashing a console
# window every 30 minutes. It needs a privilege that not every account has, so
# fall back to an interactive principal rather than failing.
$userId = "$env:USERDOMAIN\$env:USERNAME"
$principals = @(
    (New-ScheduledTaskPrincipal -UserId $userId -LogonType S4U -RunLevel Limited),
    (New-ScheduledTaskPrincipal -UserId $userId -LogonType Interactive -RunLevel Limited)
)

$usedFallback = $false
foreach ($name in $Tasks.Keys) {
    $action = New-ScheduledTaskAction -Execute 'cmd.exe' `
        -Argument "/c `"$Wrapper`" $name" -WorkingDirectory $Root

    $registered = $false
    for ($i = 0; $i -lt $principals.Count; $i++) {
        try {
            Register-ScheduledTask -TaskName $name -TaskPath $TaskFolder `
                -Action $action -Trigger $Triggers[$name] -Settings $Settings `
                -Principal $principals[$i] -Description $Tasks[$name] -Force | Out-Null
            if ($i -gt 0) { $usedFallback = $true }
            $registered = $true
            break
        } catch {
            if ($i -eq $principals.Count - 1) { throw }
        }
    }
    if ($registered) { Write-Host "  registered $name" }
}

# ── report ───────────────────────────────────────────────────────────────────

Write-Host ''
Write-Host 'installed. Your schedule is now:'
Write-Host ''
Write-Host '  07:07 daily      crawl         jobs, scoring, materials'
Write-Host '  every 30 min     publish-due   publishes anything whose slot arrived'
Write-Host '  Sun 18:00        weekly        drafts next week, refreshes the token'
Write-Host '  2 min after logon catchup      replays what was missed'
Write-Host ''
Write-Host 'Notes:'
Write-Host "  - Drafts never publish on their own. 'weekly' only drafts."
Write-Host '    You approve with: lgrow posts review'
Write-Host "  - Logs: $LogDir\schedule.log"
Write-Host "  - Inspect:  Get-ScheduledTask -TaskPath '$TaskFolder'"
Write-Host "  - Run one now:  Start-ScheduledTask -TaskPath '$TaskFolder' -TaskName crawl"
Write-Host '  - Remove with:  powershell -ExecutionPolicy Bypass -File scripts\install-schedule.ps1 remove'
Write-Host ''

if (-not $GeminiDir) {
    Write-Warning @'
'gemini' was not on your PATH when this ran, so scheduled AI calls will fail.
Install it and re-run this script:
    npm install -g @google/gemini-cli
'@
}

if ($usedFallback) {
    Write-Warning @'
Registered with an interactive principal: this account cannot use S4U. The
tasks work, but a console window will flash briefly on each run.
'@
}

if (-not (Test-Path (Join-Path $Root '.env'))) {
    Write-Warning 'no .env found. Publishing will fail until you add your LinkedIn credentials.'
}
