#!/usr/bin/env bash
#
# Install (or refresh) lgrow's cron schedule.
#
# Idempotent: every line it writes is fenced between marker comments, so
# re-running replaces the block rather than duplicating it. Run with `remove` to
# take it out again.
#
# The reason this generates a wrapper script instead of putting commands
# straight into crontab: cron runs with a near-empty PATH and no profile, so
# `gemini` (installed under nvm) would not be found and every AI call would fail
# with an auth error that looks like a login problem. The wrapper pins the PATH
# that exists right now, at install time.

set -euo pipefail

BEGIN_MARK="# >>> lgrow schedule >>>"
END_MARK="# <<< lgrow schedule <<<"

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
root="$(cd "$here/.." && pwd)"
wrapper="$root/scripts/lgrow-cron.sh"

# Prefer the project venv; fall back to whatever `lgrow` is on PATH.
if [[ -x "$root/.venv/bin/lgrow" ]]; then
  lgrow_bin="$root/.venv/bin/lgrow"
elif command -v lgrow >/dev/null 2>&1; then
  lgrow_bin="$(command -v lgrow)"
else
  echo "error: cannot find lgrow. Install it first:" >&2
  echo "    cd '$root' && python3 -m venv .venv && ./.venv/bin/pip install -e ." >&2
  exit 1
fi

action="${1:-install}"

remove_block() {
  if crontab -l 2>/dev/null | grep -qF "$BEGIN_MARK"; then
    crontab -l 2>/dev/null \
      | awk -v b="$BEGIN_MARK" -v e="$END_MARK" '
          $0==b {skip=1} !skip {print} $0==e {skip=0}' \
      | crontab -
    echo "removed the existing lgrow block from your crontab"
  fi
}

if [[ "$action" == "remove" ]]; then
  remove_block
  echo "done. lgrow will no longer run on a schedule."
  exit 0
fi

# ── the wrapper ──────────────────────────────────────────────────────────────
gemini_path=""
if command -v gemini >/dev/null 2>&1; then
  gemini_path="$(dirname "$(command -v gemini)")"
fi

cat > "$wrapper" <<WRAPPER
#!/usr/bin/env bash
# Generated by scripts/install-cron.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# Re-run that script if node/nvm moves and the Gemini CLI stops being found.
set -uo pipefail

# cron gives us almost no PATH. This is the PATH captured at install time,
# which is what makes \`gemini\` reachable from a scheduled run.
export PATH="${gemini_path:+$gemini_path:}$PATH"
export LGROW_HOME="$root"

# Gemini CLI keeps its OAuth credentials under \$HOME; without this a cron run
# looks unauthenticated even though you logged in interactively.
export HOME="\${HOME:-$HOME}"

exec "$lgrow_bin" run "\$@"
WRAPPER
chmod +x "$wrapper"
echo "wrote $wrapper"

# ── the crontab block ────────────────────────────────────────────────────────
# Times are local. Deliberately off the hour so we're not competing with every
# other cron job on the machine at :00.
block="$(cat <<CRON
$BEGIN_MARK
# Managed by scripts/install-cron.sh — edit there, not here.
# Fetch, score and queue jobs; prepare materials for the best matches.
7 7 * * *    $wrapper crawl >> $root/data/logs/cron.log 2>&1
# Publish anything whose scheduled slot has arrived (one post per run).
*/30 * * * * $wrapper publish-due >> $root/data/logs/cron.log 2>&1
# Sunday evening: draft next week's posts, refresh the token, list follow-ups.
0 18 * * 0   $wrapper weekly >> $root/data/logs/cron.log 2>&1
# Replay whatever was missed while this machine was asleep or shut down.
@reboot      sleep 120 && $wrapper catchup >> $root/data/logs/cron.log 2>&1
$END_MARK
CRON
)"

remove_block
{ crontab -l 2>/dev/null || true; echo "$block"; } | crontab -

mkdir -p "$root/data/logs"

echo
echo "installed. Your schedule is now:"
echo
crontab -l | sed -n "/$(printf '%s' "$BEGIN_MARK" | sed 's/[][\\/.*^$]/\\&/g')/,/$(printf '%s' "$END_MARK" | sed 's/[][\\/.*^$]/\\&/g')/p" \
  | grep -v '^#' | sed 's/^/  /'
echo
echo "Notes:"
echo "  · Drafts never publish on their own — 'weekly' only drafts."
echo "    You approve with: lgrow posts review"
echo "  · Logs: $root/data/logs/cron.log"
echo "  · Remove with: $here/install-cron.sh remove"
echo
if [[ -z "$gemini_path" ]]; then
  echo "  WARNING: 'gemini' was not on your PATH when this ran, so scheduled AI"
  echo "  calls will fail. Install it and re-run this script:"
  echo "      npm install -g @google/gemini-cli"
fi
